
//SUBIR LA IMAGEN
export const SUBIR_IMAGEN = 'SUBIR_IMAGEN';
export const SUBIR_IMAGEN_EXITO = 'SUBIR_IMAGEN_EXITO';

//CAMBIO AL FORMULARIO
export const AGREGAR_TITULO = 'AGREGAR_TITULO';
export const AGREGAR_CATEGORIA = 'AGREGAR_CATEGORIA';
export const AGREGAR_DESCRIPCION = 'AGREGAR_DESCRIPCION';
export const AGREGAR_IMG ='AGREGAR_IMG';

//ALERTAS PARA EL FORMULARIO
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

//OBTENER IMAGENES Y POR CATEGORIA
export const OBTENER_IMAGENES = 'OBTENER_IMAGENES';
export const OBTENER_CATEGORIA = 'OBTENER_CATEGORIA';

//ELIMINAR IMAGEN
export const ELIMINAR_IMAGEN = 'ELIMINAR_IMAGEN';

//LIMPIAR ESTADOS
export const LIMPIAR_ESTADOS = 'LIMPIAR_ESTADOS';
export const LIMPIAR_ESTADO_BUSQUEDA = 'LIMPIAR_ESTADO_BUSQUEDA';

